### ISSUE TITLE
Volume state appears in notify-osd when stopping playback.

### ISSUE THREAD

**Issue by elric** [KittyKatt/mpd-libnotify#1]
Hello:
First, thanks for the awesome app I've been searching for so long. A good mpd notifier :)

Now, sadly, the issue, almost entirely described in the title. The volume state appears after a few seconds from stopping playback. This is what I get with mpc and ncmpcpp

volume:+37%+++repeat:+off+++random:+off+++single:+off+++consume:+off

I get this under every entry in the notification (from, by, etc..). Isn't there a way to make your program "deaf" to certain mpd states, like pause and stop? (there is another extra notification there)

**Comment by KittyKatt** [comment]
For myself, it shows only one notification per song change / stopping playback. My setup is a little out of the ordinary, however. I'll test it with a generic MPD+mpc setup in a bit an report back.

Have you modified the config that is generated on first run at all? If so, could you please gist it for me and paste a link here?

I actually have some new changes to push to github soon dealing with parsing the titles and such. I'd love to add a fix for your problem in with this commit if it really is a bug.

**Comment by elric** [comment]
Hope I did the gist right. Don't get me wrong, I'm a translator with a small knowledge in this matters.

https://gist.github.com/f82301a09eb265abbcf5

In the installation script, I had to modify the variable $XDG_... (the one pointing to home), and insert $HOME, otherwise, it didn't have permissions to create the folder. I do have xdg-user\* packages installed. I did the rest of modifications to the conf file.

**Comment by KittyKatt** [comment]
You only pasted part of your config into the input box. I'm starting up a Virtual Machine in a moment to attempt to duplicate your error. Could you give me some specifics on what your current environment is? Distro? I'll assume you're using notify-osd instead of notification-daemon as that is in the post title.

**Comment by elric** [comment]
Sorry, that was a mistake born from habit. I do use notification-daemon with Gnome on Debian amd64. mpdnotify is in my path. I do not autostart mpd or anything. 
you said

> For myself, it shows only one notification per song change / stopping playback

Same here, but also for pausing and resuming the song. Stopping playback notification seemed strange to me.
Sorry for the gist thing.
https://gist.github.com/673427

**Comment by KittyKatt** [comment]
That in itself is a flaw in MPD's idle protocol. It will push a 'player' event at a listening client on any playback change whose output is simply 'player', afaik. I have not found a way to differentiate between a 'prev/next' and a 'play/pause/stop'. Also, when you issue 'stop' the song title is no longer in the mpc output, so that's why you're getting a strange notification when that happens. It happens for me as well.

I'm experimenting with communicating with MPD directly, bypassing clients like mpc and ncmpcpp completely, via TCP sockets in Bash, fwiw. Not a lot of progress so far, but it looks promising.

**Comment by elric** [comment]
Thanks for your efforts :) Just shout if you want some testing.

**Comment by KittyKatt** [comment]
Will do, thanks for the feedback! Always welcome.
